name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests-dusk:
    name: Browser Tests
    runs-on: ubuntu-latest
    container: docker://chilio/laravel-dusk-ci:latest
    services:
      mysql:
        image: mariadb:10.4
        env:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: skeleton_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=2s --health-timeout=2s --health-retries=2
    steps:
      - name: Check out my repo
        uses: actions/checkout@master
        with:
          repository: Yurich84/laravel-vue-spa-skeleton
      - name: Download Node Dependencies
        run: yarn
      - name: Build
        run: yarn run prod
      - name: Download PHP Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: Setup Laravel
        run: |
          configure-laravel
          php artisan dusk:install
          php artisan dusk:chrome-driver --all
          chmod -R 0755 vendor/laravel/dusk/bin/
          php artisan serve --env=dusk.local > /dev/null 2>&1 &
      - name: Run dusk tests
        run: php artisan dusk --env=dusk.local
      - uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tests/Browser/screenshots
