name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  assets:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: Yurich84/laravel-vue-spa-skeleton
      - name: Download Dependencies
        run: yarn
      - name: Build
        run: yarn run prod
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: assets
          path: public
  tests-dusk:
    name: Browser Tests
    needs: assets
    runs-on: ubuntu-latest
    container: docker://chilio/laravel-dusk-ci:stable
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306/tcp
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: skeleton_test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: Yurich84/laravel-vue-spa-skeleton
      - name: Download build assets
        uses: actions/download-artifact@v1
        with:
          name: assets
          path: public
      - name: Download Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan dusk:update --detect
          configure-laravel
          start-nginx-ci-project
      - name: Run dusk tests
        run: php artisan dusk
